pages = pages || {};
pages.manageUsers = `<div class='text-center py-10'><h1 class='text-2xl font-bold'>Manage Users</h1><p>View and control user accounts.</p></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-primary'>View All Users</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-secondary'>Add New User</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-warning'>Edit User</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-danger'>Delete User</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-info'>Search User</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-success'>Export User Data</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-dark'>View User Activity Logs</button></div>`;
pages.manageUsers += `<div class='flex justify-center mt-10'><button class='btn btn-link'>Back to Admin Dashboard</button></div>`;
pages.manageUsers += `<div class='text-center mt-10'><p>&copy; 2025 ExportLink. All rights reserved.</p></div>`;    