pages = pages || {};
pages.orderManagement = `<div class='text-center py-10'><h1 class='text-2xl font-bold'>Order Management</h1><p>Track and manage orders here.</p></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-primary'>View All Orders</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-secondary'>Add New Order</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-success'>Edit Order</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-warning'>Delete Order</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-info'>Search Order</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-dark'>Export Order Data</button></div>`;
pages.orderManagement += `<div class='flex justify-center mt-10'><button class='btn btn-link'>Back to Admin Dashboard</button></div>`;
pages.orderManagement += `<div class='text-center mt-10'><p>&copy; 2023 ExportLink. All rights reserved.</p></div>`;    